### ISSUE TITLE
Verify: After resetting my password I'm directed to api.serpconnect

### ISSUE THREAD

**Issue by emenlu** [emenlu/website#11]

**Comment by murlocbrand** [comment]
The password reset process is:

 - user requests password reset on login page
  - server sends email with password reset token
 - user clicks on reset url in email
  - server generates a new password and emails it to the user
 - user copies the new password and can login

A better approach is to:

 - user requests password reset on login page
  - server sends email with password reset token
 - user clicks on reset url in mail
  - user inputs new password
 - user is logged in automatically

But this requires some work, probably around 1~2 hrs.

**Comment by murlocbrand** [comment]
@Drullan implemented emenlu/connect#11
