### ISSUE TITLE
Verify: No stats available

### ISSUE THREAD

**Issue by emenlu** [emenlu/website#13]

**Comment by murlocbrand** [comment]
Stats might need a checkup, to see if the behaviour is correct:

- nbr. of users in collection = users with relation (:MEMBER_OF) to collection
- nbr. of entries in collection = non-pending entries with relation (:CONTAINS) to collection

Which means that invited users and pending entries aren't counted until they accept/are approved.

**Comment by murlocbrand** [comment]
If :arrow_up:  is ok then we can close the issue

**Comment by smetz** [comment]
@emenlu what stats do you want to see? Imagine something like `10 users/56 entries`, what does `10 users` and `56 entries` actually refer to? The current definitions are in the comment above. Do they make any sense?

**Comment by emenlu** [comment]
I'm afraid i have forgotten the origin of this comment. Users refers to #members of a collection and entries to #entries in a collection. Maybe change users to members. Otherwise I think it is ok as it is.

**Comment by smetz** [comment]
ok, that is the current behavior!
