### ISSUE TITLE
Unintentionally creating many collections with the same name on submit page

### ISSUE THREAD

**Issue by emenlu** [emenlu/website#17]
Many collections with the same name.

I tried to enter a number of entries starting by creating a new collection and then added entries to the queue. What I didn't notice was that I created a new collection for each element. 

- Should it be possible to have several collections with the same name? 
- default should never be to create a new collection 
- is there a way to merge several collections into one?

**Comment by murlocbrand** [comment]
Also here https://github.com/emenlu/connect/issues/3

**Comment by murlocbrand** [comment]
- Need to do #21 first
