### ISSUE TITLE
Enter doi -> auto complete reference

### ISSUE THREAD

**Issue by emenlu** [emenlu/website#18]

**Comment by smeetz** [comment]
Maybe we can get this up and running using `crossref.org`. I tested an example:

http://api.crossref.org/works/10.1109/MS.2014.56

**Comment by smeetz** [comment]
Closing for now, we can reopen when this is important. Integration with zotero is higher prio for now

**Comment by smeetz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DOI to reference autocomplete](https://trello.com/c/xFPQIVCH/124-doi-to-reference-autocomplete)
