### ISSUE TITLE
Hide autocomplete screen reader div on submit page

### ISSUE THREAD

**Issue by emenlu** [emenlu/website#20]
Or change autocomplete framework

**Comment by emenlu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#20 Hide autocomplete screen reader div on submit page](https://trello.com/c/gs0QLwNl/20-20-hide-autocomplete-screen-reader-div-on-submit-page)

**Comment by smetz** [comment]
This was probably fixed by 24ded38d0f8b5e83abb71afff08a3ecf178b05a0
