### ISSUE TITLE
Fix unsafe requests when connecting to website using HTTPS

### ISSUE THREAD

**Issue by smeetz** [emenlu/website#30]
Right now users have to allow unsafe requests when accessing the website over HTTPS, because some resources (d3?) are always loaded over HTTP.

Either we force all resources over HTTPS or use the more dynamic `//` (current protocol).

**Comment by smetz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#30 Fix unsafe requests when connecting to website using HTTPS](https://trello.com/c/qVzjzbP6/53-30-fix-unsafe-requests-when-connecting-to-website-using-https)

**Comment by smetz** [comment]
I think this is done, waiting for @J-Son89 to confirm.

**Comment by J-Son89** [comment]
As far as I know we resolved this issue, I will commit it shortly.
