### ISSUE TITLE
How to login/logout

### ISSUE THREAD

**Issue by emenlu** [emenlu/website#31]
As noticed on the meeting, it is hard to log out.
It shouldn't be hard.

**Comment by smetz** [comment]
I think this was fixed by 99bc8e5ee5e52035a800a7d44fad9ce1c437a0f2, but we found a bug with the placement of the login/logout text on larger screens (text floats to the right). Keeping this open until @J-Son89 has time to fix it.

**Comment by J-Son89** [comment]
Yep, I will update this asap.
