### ISSUE TITLE
Export -> new collection -> create creates an empty collection. It should create a collection out of the selected entries.

### ISSUE THREAD

**Issue by emenlu** [emenlu/website#40]

**Comment by smetz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Export -> new collection -> create creates an empty collection. It should create a collection out of the selected entries.](https://trello.com/c/M8jozK4R/69-export-new-collection-create-creates-an-empty-collection-it-should-create-a-collection-out-of-the-selected-entries)
